/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package controller

// Shared fixtures for the controller tests. One name per repeated value keeps the
// tests in agreement on what each fixture is.
const (
	testAbsent              = "absent"
	testAgree               = "agree"
	testAllow               = "allow"
	testAlpha               = "alpha"
	testAlphaDescription    = "Alpha agent"
	testArtifactsDir        = "/artifacts"
	testBaseline            = "baseline"
	testBeta                = "beta"
	testBetaDescription     = "Beta agent"
	testBias04              = "0.4"
	testBiasDefaultKey      = "default"
	testBundle              = "bundle"
	testConcern             = "concern"
	testConditionAvailable  = "Available"
	testCoord               = "coord"
	testCrewA               = "crew-a"
	testCrewHomelabPilotNS  = "crew-homelab-pilot"
	testCrewLabelTest       = "crew-label-test"
	testCrewManagedDelete   = "crew-managed-delete"
	testCrewName            = "homelab-pilot"
	testCrewNamespace       = "crew-x"
	testCrewNoLabelTest     = "crew-nolabel-test"
	testCrewNoNSDelete      = "crew-no-ns-delete"
	testCrewRBACTest        = "crew-rbac-test"
	testCrewSkillsConfigMap = "crew-homelab-pilot-skills"
	testCrewTest            = "crew-test"
	testDeadbeef            = "deadbeef"
	testDeny                = "deny"
	testDone                = "done"
	testEmpty               = "empty"
	testEnvFalse            = "false"
	testEnvTrue             = "true"
	testExact               = "exact"
	testFailureMessage      = "boom"
	testFast                = "fast"
	testFinding             = "finding"
	testFirstCrewReply      = "first-crew reply one"
	testFixtureAgent        = "test"
	testGPUAgent            = "gpu"
	testGPUAt41             = "gpu at 41%"
	testGPUProvider         = "gpu"
	testGPUSkillContent     = "WHEN asked about GPU THEN check nvidia-smi"
	testGPUUtilization      = "gpu-utilization"
	testGateway1            = "gw1"
	testHTTP                = "http"
	testHarborPullSecret    = "harbor-pull-secret"
	testHarnessLabelValue   = "true"
	testHelloWorldTitle     = "Hello World"
	testHigh                = "high"
	testHomelabCoordinator  = "homelab-coordinator"
	testIndexerImage        = "indexer:v1"
	testInvalid             = "invalid"
	testK8sAgent            = "k8s"
	testK8sNodes            = "k8s-nodes"
	testK8sPodStatus        = "k8s-pod-status"
	testKeywordK8s          = "k8s"
	testKubemoot            = "kubemoot"
	testLabelManagedBy      = "app.kubernetes.io/managed-by"
	testLatencyClass        = "latencyClass"
	testLow                 = "low"
	testMain                = "main"
	testMatcherValue        = "test"
	testMismatchName        = "other"
	testModel32B            = "qwen3:32b"
	testMulling             = "mulling"
	testMullingProviderKey  = "kubemoot.ai/mulling-provider"
	testNS1                 = "ns1"
	testNS2                 = "ns2"
	testNomicEmbed          = "nomic-embed"
	testNpx                 = "npx"
	testNtfyURL             = "https://ntfy.example.com/topic"
	testOllama              = "ollama"
	testOllamaGPU           = "ollama-gpu"
	testOllamaRig1          = "ollama-rig1"
	testOrphan              = "orphan"
	testOtherCrew           = "other"
	testOtherProvider       = "other"
	testOtherSecret         = "other"
	testOwnerName           = "owner"
	testPathAPITags         = "/api/tags"
	testPathHealth          = "/health"
	testPhaseUnschedulable  = "Unschedulable"
	testPilotArm            = "homelab-pilot"
	testPlainWord           = "test"
	testPods                = "pods"
	testProbedAt            = "2026-05-25T06:30:00Z"
	testProseArm            = "homelab-pilot-prose"
	testProviderName        = "prov"
	testRange1x             = "1.x"
	testRangeAtLeast120     = ">=1.2.0"
	testRangeAtMost120      = "<=1.2.0"
	testRangeCaret120       = "^1.2.0"
	testRangeTilde120       = "~1.2.0"
	testReasoning           = "reasoning"
	testRecommendedVersion  = "1.1"
	testReplicateSecretsKey = "kubemoot.ai/replicate-secrets"
	testRepoURL             = "https://github.com/test/repo"
	testResearcher          = "researcher"
	testRig0                = "rig0"
	testRig0URL             = "http://ollama.ollama-rig0:11434"
	testRoleCoordinator     = "coordinator"
	testRoleTooler          = "tooler"
	testRunID               = "abc"
	testRunPrefix           = "ns/suite/run/"
	testRunS0I1             = "ns/suite/run/s0-i1.json"
	testSSE                 = "sse"
	testScenarioA           = "a-scenario"
	testScenarioGPU         = "gpu"
	testScenarioX           = "scenario-x"
	testScriptContent       = "..."
	testSecondCrewReply     = "second-crew reply one"
	testSecretName          = "my-secret"
	testSheetRuns           = "Runs"
	testSheetScenarios      = "Scenarios"
	testSkill               = "skill"
	testSkillGPUBasics      = "gpu-basics"
	testSkillNetDiag        = "net-diag"
	testSkills              = "skills"
	testSomeoneElse         = "someone-else"
	testSourceSuite         = "src"
	testStandAside          = "stand_aside"
	testSuite               = "suite"
	testSynthesis           = "synthesis"
	testSynthesisNonEmpty   = "synthesis is non-empty"
	testTheAnswer           = "the answer"
	testTier                = "tier"
	testToolCalling         = "tool-calling"
	testToolKubectlGet      = "kubectl_get"
	testUnchangedName       = "simple"
	testUnknown             = "unknown"
	testVerdictReflects     = "REFLECTS"
	testVersion100          = "1.0.0"
	testVersion120          = "1.2.0"
	testVersion123          = "1.2.3"
	testVersion130          = "1.3.0"
	testVersion142          = "1.4.2"
	testVersion200          = "2.0.0"
)
