apiVersion: v2
name: kubemoot-operator
description: Kubernetes operator and runtime for multi-agent AI consensus
type: application
version: 0.92.582-rc.1
appVersion: "0.344.0-rc.1"
keywords:
  - ai
  - ml
  - operator
  - llm
  - kubernetes
home: https://github.com/kubemoot/kubemoot
sources:
  - https://github.com/kubemoot/kubemoot
maintainers:
  - name: Kubemoot maintainers
    email: moot@kubemoot.org
